server:
  port: 8080

basket:
  host: basket:8080

inventory:
  host: inventory:8080

user:
  host: user:8080

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system:14268